const $=s=>document.querySelector(s);let notices=[],performances=[];
function toast(message,error=false){const n=$('#toast');n.textContent=message;n.style.background=error?'#9b2929':'';n.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.classList.remove('show'),2600)}
function val(form,name){return form.elements[name].value.trim()}function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showApp(){loginView.hidden=true;appView.hidden=false;loadAll()}function showLogin(){loginView.hidden=false;appView.hidden=true}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginMessage.textContent='로그인 중…';try{const r=await kijApi.login(val(loginForm,'username'),val(loginForm,'password'));kijApi.token=r.token||r.accessToken;if(!kijApi.token)throw Error('로그인 토큰이 없습니다.');loginMessage.textContent='';showApp()}catch(x){loginMessage.textContent=x.message}});logoutButton.onclick=()=>{kijApi.token='';showLogin()};
document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-button,.panel').forEach(n=>n.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active');pageTitle.textContent=b.textContent+' 관리'});document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{const f=$('#'+b.dataset.reset);f.reset();f.elements.id.value='';if(f.id==='noticeForm')f.elements.date.valueAsDate=new Date()});
async function loadAll(){await Promise.allSettled([loadNotices(),loadOrganization(),loadPerformances()])}async function loadNotices(){try{notices=await kijApi.notices();renderNotices()}catch(x){noticeList.innerHTML=`<p class="empty">${esc(x.message)}</p>`}}function renderNotices(){noticeCount.textContent=`${notices.length}건`;noticeList.innerHTML=notices.sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(i=>`<article class="record"><div><h3>${esc(i.title)}</h3><p>${esc(i.date)} · ${i.published===false?'비공개':'공개'}\n${esc(i.content).slice(0,120)}</p></div><div class="record-actions"><button data-edit-notice="${i.id}">수정</button><button class="delete" data-delete-notice="${i.id}">삭제</button></div></article>`).join('')||'<p class="empty">등록된 공지가 없습니다.</p>'}
noticeForm.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=val(f,'id'),data={title:val(f,'title'),date:val(f,'date'),content:val(f,'content'),published:f.elements.published.checked};try{id?await kijApi.updateNotice(id,data):await kijApi.createNotice(data);f.reset();f.elements.id.value='';f.elements.date.valueAsDate=new Date();await loadNotices();toast('공지사항을 저장했습니다.')}catch(x){toast(x.message,true)}};noticeList.onclick=async e=>{const edit=e.target.dataset.editNotice,del=e.target.dataset.deleteNotice;if(edit){const i=notices.find(r=>String(r.id)===edit),f=noticeForm;['id','title','date','content'].forEach(n=>f.elements[n].value=i[n]||'');f.elements.published.checked=i.published!==false;scrollTo({top:0,behavior:'smooth'})}if(del&&confirm('이 공지사항을 삭제할까요?'))try{await kijApi.deleteNotice(del);await loadNotices();toast('삭제했습니다.')}catch(x){toast(x.message,true)}};
async function loadOrganization(){try{const d=await kijApi.organization();if(d?.imageUrl)organizationPreview.src=d.imageUrl}catch(x){console.info('기존 조직도 사용:',x.message)}}organizationForm.elements.image.onchange=e=>{const f=e.target.files[0];if(f)organizationPreview.src=URL.createObjectURL(f)};organizationForm.onsubmit=async e=>{e.preventDefault();try{await kijApi.updateOrganization(new FormData(e.currentTarget));toast('조직도를 변경했습니다.')}catch(x){toast(x.message,true)}};
async function loadPerformances(){try{performances=await kijApi.performances(performanceFilter.value);renderPerformances()}catch(x){performanceList.innerHTML=`<p class="empty">${esc(x.message)}</p>`}}function renderPerformances(){performanceList.innerHTML=performances.sort((a,b)=>(b.year-a.year)||(a.sortOrder-b.sortOrder)).map(i=>`<article class="record"><div><h3>${esc(i.title)}</h3><p>${esc(i.year)} · ${esc(i.category)}</p></div><div class="record-actions"><button data-edit-performance="${i.id}">수정</button><button class="delete" data-delete-performance="${i.id}">삭제</button></div></article>`).join('')||'<p class="empty">등록된 실적이 없습니다.</p>'}performanceFilter.onchange=loadPerformances;performanceForm.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=val(f,'id');try{id?await kijApi.updatePerformance(id,new FormData(f)):await kijApi.createPerformance(new FormData(f));f.reset();f.elements.id.value='';await loadPerformances();toast('실적을 저장했습니다.')}catch(x){toast(x.message,true)}};performanceList.onclick=async e=>{const edit=e.target.dataset.editPerformance,del=e.target.dataset.deletePerformance;if(edit){const i=performances.find(r=>String(r.id)===edit),f=performanceForm;['id','category','year','title','sortOrder'].forEach(n=>f.elements[n].value=i[n]??'');scrollTo({top:0,behavior:'smooth'})}if(del&&confirm('이 실적을 삭제할까요?'))try{await kijApi.deletePerformance(del);await loadPerformances();toast('삭제했습니다.')}catch(x){toast(x.message,true)}};
noticeForm.elements.date.valueAsDate=new Date();kijApi.token?showApp():showLogin();
